import type { Metadata } from "next";
import "./globals.css";
import NavBar from "./Components/NavBar";

import { Mulish } from "next/font/google";
import Footer from "./Components/Footer";

// Load the Mulish font
export const mulish = Mulish({
  subsets: ["latin"], // Include desired subsets
  weight: ["400", "700"], // Add desired weights
  variable: "--font-mulish", // Add a CSS variable for better integration
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${mulish.variable} antialiased`}
      >
        <div>
          <NavBar></NavBar>
        </div>
        {children}
        <div>
          <Footer></Footer>
        </div>
      </body>
    </html>
  );
}
