import type { Metadata } from "next";
import "./globals.css";
import NavBar from "./Components/NavBar";
import Footer from "./Components/Footer";

import { Mulish } from "next/font/google";

// Configure and load the Mulish font
 const mulish = Mulish({
  subsets: ["latin"], // Define subsets for the font
  weight: ["400", "700"], // Specify weights
  variable: "--font-mulish", // Define a CSS variable for the font
});

// Metadata for the application
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Root layout definition
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="light" className={mulish.variable}> {/* Use the font variable here */}
      <body className="antialiased"> {/* Keep global body styles */}
        <div>
          <NavBar /> {/* Render NavBar */}
        </div>
        <main>{children}</main> {/* Render children inside main */}
        <div>
          <Footer /> {/* Render Footer */}
        </div>
      </body>
    </html>
  );
}
